# Generated by Django 5.2.13 on 2026-06-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_account_number_user_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reseller_status',
            field=models.CharField(choices=[('NONE', 'None'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NONE', max_length=20),
        ),
    ]
