# Generated by Django 5.2.13 on 2026-06-01 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_reseller_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResellerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media_link', models.URLField(blank=True, help_text='Link Instagram, TikTok, atau toko online Anda')),
                ('marketing_plan', models.TextField(help_text='Bagaimana Anda berencana memasarkan produk kami?')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseller_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
